config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'

  resources :users do
    resources :posts do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[new create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    if user.present?
      can :create, Post
      can :update, Post, Author_id: user.id
      can :destroy, Post, Author_id: user.id

      can :create, Comment
      can :update, Comment, users_id: user.id
      can :destroy, Comment, users_id: user.id
    end

    return unless user.role == 'admin'

    can :manage, :all

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'users_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'posts_id'

  after_save :comments_updater
  after_destroy :comments_updater

  def comments_updater
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'users_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'posts_id'

  after_save :likes_updater
  after_destroy :likes_updater

  def likes_updater
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'Author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'posts_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'posts_id', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :post_updater
  after_destroy :post_updater

  def post_updater
    author.update(posts_counter: author.posts.count)
  end

  def comments_recent
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'Author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'users_id'
  has_many :likes, class_name: 'Like', foreign_key: 'users_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def post_recent
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_data)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])

    if @comment.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def destroy
    activeuser = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    comment = Comment.find(params[:id])
    if comment.destroy
      # flash[:success] = 'The Post was deleted successfully!'
      redirect_to user_posts_path(activeuser)
    else
      # flash[:error] = 'Error! The Post was not deleted'
      redirect_to user_post_path(activeuser, post)
    end
  end

  private

  def comment_data
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def new
    @like = Like.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new(author: current_user, post: @post)

    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @author = User.find(params[:user_id])
    @posts = @author.posts.includes(:comments)
  end

  def show
    @author = User.find(params[:user_id])
    @author_posts = @author.posts
    @post = @author_posts.find(params[:id])
    @like = Like.new
    @comment = Comment.new
  end

  def new
    @author = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_data)

    if @post.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    activeuser = params[:user_id]
    if post.destroy
      #  flash[:success] = 'The Post was deleted successfully!'
      redirect_to user_posts_path(activeuser)
    else
      #  flash[:error] = 'Error! The Post was not deleted'
      redirect_to user_post_path(activeuser, post)
    end
  end

  private

  def post_data
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<div class="con">
<%= form_with(model: [@author, @post, @comment], url: user_post_comments_path(@author, @post), method: :post) do |form| %>
  <div class="testArea">
     <% form.label :text %>
     <%= form.text_area :text %>
  </div>

  <div class="con">
    <%= form.submit 'Add Comment', class: 'btn' %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="credentials">
    <% if user_signed_in? %>
      <button class='buttonsCred'><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %></button>
    <% else %>
      <p> If you have account, you can <button class='buttonsCred'><%= link_to 'Sign In', new_user_session_path %></button></p>
      <p> If not, you can create new one<button class='buttonsCred'><%= link_to 'Sign Up', new_user_registration_path %></button></p>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/partials/_destroy_comment.html.erb
<% if can?(:destroy, comment) %>
      <%= button_to 'Delete comment', user_post_comment_path(post.author, post, comment), method: :delete, remote: true %>
<% end %>

app/views/partials/_destroy_post.html.erb
<% if can?(:destroy, post) %>
      <%= button_to 'Delete Post', user_post_path(post.author, post), method: :delete, remote: true %>
<% end %>

app/views/posts/index.html.erb
<div class="container user">
      <div class="userPhoto margin"><%= image_tag("#{@author.photo}", alt: 'Imagen externa') %></div>
      <div class="userInfo margin">
        <h2><%= @author.name %></h2>
        <p><%= "Number of posts: #{@author.posts_counter}"%></p>
      </div>
</div>

<% @posts.each do |post|%>
  <div class="margin posts">
    <div class="comments">
    <h3><%= link_to "Post # #{post.id}", user_post_path(@author.id, post.id)%></h3>
    <%= render 'partials/destroy_post', post: post %>
    </div>
    <p><%=post.text%></p>
    <i><%="Comments #{post.comments_counter}, Likes #{post.likes_counter}"%></i>
  </div>
  <div class="margin bio">
    <h2>Comments</h2>
    <% post.comments.each do |comment|%>
      <div class="comments">
      <%= "#{comment.author.name}: #{comment.text}"%><br><br>
      <%= render 'partials/destroy_comment', post: post, comment: comment %>
      </div>
    <%end%>
  </div>  
<%end%>

<div class="container">
  <button class='button_footer'><%= link_to 'Create new Post', new_user_post_path(@author) %></button>    
  <button type="button" class='button_footer two'>Pagination</button>
</div>

app/views/posts/new.html.erb
<%= form_with(model: [@author, @post], url: user_posts_path(@author), method: :post) do |form| %>
    <div class="margin posts form">
        <h2>Create New Post for <%= @author.name %></h2>
          <div class="form">
            <%= form.label :title %>
            <%= form.text_field :title %>
          </div>
  
          <div class="form">
            <%= form.label :text %>
            <%= form.text_area :text %>
          </div>
  
          <div class="form">
            <%= form.submit 'Create Post' %>
          </div>
    </div>
  <% end %>

app/views/posts/show.html.erb
<div class="container margin desc">
  <h1><%="Post #{@post.id} by #{@post.author.name}"%></h1>
  <i><%="Comments: #{@post.comments_counter}, Likes #{@post.likes_counter}"%></i>
  <p>Title of post: <%=@post.title%></p> 
  <p><%=@post.text%></p>  
</div>

<div class="posts margin contComm">
  <h2>Comments</h2>
    <% @post.comments.each do |comment|%>
      <div class="comments">
      <%= "#{comment.author.name}: #{comment.text}"%><br /><br />
      <%= render 'partials/destroy_comment', post: @post, comment: comment %>
      </div>
    <%end%>
</div>

<div class="form">
   <%= render 'comments/form' %>
</div>

<div class="form">
<%= form_with(model: [@author, @post, @like], url: user_post_likes_path(@author, @post), method: :post) do |form| %>
  <%= form.submit 'Gift a like', class: 'button_footer' %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="indexTitle margin">
Welcome to the famous page blog whitout importance
</div>

<% @users.each do |user| %>
    <div class="container user">
      <div class="userPhoto margin"><%= image_tag("#{user.photo}", alt: 'Profile picture') %>
      </div>
      <div class="userInfo margin">
        <h2><%= link_to user.name, user %></h2>
        <p><%= "Number of posts: #{user.posts_counter}"%></p>
      </div>
    </div>
<% end %>

app/views/users/show.html.erb
<div class="container user">
      <div class="userPhoto margin"><%= image_tag("#{@users.photo}", alt: 'Profile picture') %></div>
      <div class="userInfo margin">
        <h2><%= @users.name %></h2>
        <p><%= "Number of posts: #{@users.posts_counter}"%></p>
      </div>
</div>

<div class="margin bio">
  <h3>Bio</h3><br>
  <p><%= @users.bio%></p>
</div>

<% @users.post_recent.each do |post|%>
  <div class="margin posts">
    <h3><%= link_to "Post # #{post.id}", user_post_path(@users, post.id) %></h3>
    <br><p><%= post.text %></p>
    <br><i><%= "Comments #{post.comments_counter}, Likes #{post.likes_counter}"%></i>
  </div>
<%end %>

<div class="container">
  <button class='button_footer'><%= link_to 'Create new Post', new_user_post_path(@users) %></button> 
  <%= link_to 'See all posts', user_posts_path(@users), class: 'button_footer' %>
</button>